config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: "home#index"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create"
  delete :logout, to: "sessions#destroy"
  get :cart, to: "cart#index"
  post "products/:product_id/rating", to: "rates#rating", as: :product_rating
  get "add_cart/:id_product", to: "sessions#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "sessions#remove_cart", as: :remove_cart
  put "update_cart", to: "sessions#update_cart", as: :update_cart
  put "update_hard_cart", to: "sessions#update_hard_cart", as: :update_hard_cart

  resources :orders, only: %i(index create)
  resources :history, only: :index
  resources :products, only: %i(index show)
  resources :categories, only: :show
  namespace :admin do
    resources :orders, only: %i(index show) do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :categories, except: %i(new create) do
      member do
        get "new", to: "categories#new", as: :new
        post "new", to: "categories#create", as: :create
      end
      resources :products
    end

    get :import_product, to: "products#import", as: :product_import
    post :import_product, to: "products#import_process", as: :product_import_process

    resources :charts, only: :index
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :user

  enum status: {pending: 0, rejected: 1, approved: 2}

  CHART_TYPE = {"#{I18n.t("layout.admin.day")}": "day",
                "#{I18n.t("layout.admin.month")}": "month"}

  VALID_PHONE_NUMBER_REGEX = /\d[0-9]\)*\z/
  validates :name, presence: true,
    length: {maximum: Settings.user.name_max_length}
  validates :phone_number, presence: true,
    length: {maximum: Settings.user.phone_number_max_length},
    format: {with: VALID_PHONE_NUMBER_REGEX}
  validates :address, presence: true,
    length: {maximum: Settings.user.address_max_length}

  scope :order_by_time, ->{order created_at: :desc}
  scope :by_status, ->(status){where status: status if status.present?}
  scope :order_by_status, ->{order status: :asc}
  scope :where_by_email_name_address, lambda{|query|
    joins(:user).where("users.email LIKE ? OR orders.address LIKE ?
    OR orders.name LIKE ?", "%#{query}%", "%#{query}", "%#{query}%")
  }
  scope :have_products, ->(products){joins(:order_details).where("order_details.product_id": products)}
  scope :range, ->(start_date, end_date){where updated_at: start_date..end_date}
  scope :by_year, ->(day_of_year){where updated_at: day_of_year.beginning_of_year..day_of_year.end_of_year}
  scope :by_month, ->(day_of_month){where updated_at: day_of_month.beginning_of_month..day_of_month.end_of_month}
  scope :data_history, ->{joins(:order_details).joins(order_details: :product)
                          .select("orders.user_id, GROUP_CONCAT(' ', products.name, '(', order_details.quantity, ')')
                          as products_name, orders.id, orders.created_at, orders.status,
                          sum(order_details.price*order_details.quantity) as total")}
  def created_format
    created_at.strftime(Settings.order.format_time)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  include ApplicationHelper

  load_and_authorize_resource

  def index
    @params_search = params[:order] || {status: "", name_or_address_or_email: ""}
    @orders = Order.by_status(@params_search[:status])
                   .where_by_email_name_address(@params_search[:name_or_address_or_email])
                   .order_by_status
                   .order_by_time.page(params[:page])
                   .per(Settings.order.per_page)
  end

  def show
    @details = @order.order_details.includes(:product)
  end

  def approve
    @order.approved!
    # OrderMailer.approved_email(@order.user).deliver
    ApproveMailWorker.perform_async(@order.id.to_s)
    redirect_to admin_order_path(@order), success: t("controller.order.approve_success")
  end

  def reject
    @order.rejected!
    unless rollback_quantity @order
      @order.pending!
      redirect_to admin_order_path(@order), notice: t("controller.order.error_update")
      return
    end
    # OrderMailer.rejected_email(@order.user).deliver
    RejectMailWorker.perform_async(@order.id.to_s)
    redirect_to admin_order_path(@order), success: t("controller.order.reject_success")
  end

  private

  def rollback_quantity order
    OrderDetail.transaction do
      begin
        order.order_details.each do |detail|
          detail.product.increment!(:quantity, detail.quantity)
        end
      rescue StandardError
        return false
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ApplicationHelper

  layout "home"

  before_action :authenticate_user!
  before_action :check_available_product_to_order, only: %i(index create)

  authorize_resource

  def index
    @order = Order.new
  end

  def create
    @order = current_user.orders.new order_params
    if @order.save
      details = []
      current_cart.each do |product|
        detail = @order.order_details.new product_id: product.id,
          quantity: product.quantity_in_cart, price: product.price
        details << detail
      end
      details = OrderDetail.import details
      session[:cart] = {}
      update_product_quantity @order
      redirect_after_import details
    else
      render :index, notice: t("layout.order.order_fails")
    end
  end

  private

  def order_params
    params.require(:order).permit :name, :address, :phone_number
  end

  def redirect_after_import details
    flash[:notice] = if details.failed_instances.any?
                       t("layout.order.order_some_fails")
                     else
                       t("layout.order.order_success")
                     end
    redirect_to root_path
  end

  def ensure_login
    return if current_user
    flash[:danger] = t("controller.order.login_pls")
    redirect_to root_path
  end

  def update_product_quantity order
    order.order_details.each do |detail|
      detail.product.decrement!(:quantity, detail.quantity) if detail.persisted?
    end
  end
end

app/views/admin/orders/index.html.slim
.panel.panel-default
  .panel-heading
    = t("layout.order.header_index")
  .panel-body
    #dataTables-example_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer
      .row
        .col-sm-6
        .col-sm-6
          #dataTables-example_filter.dataTables_filter
            = form_for :order, method: :get do |f|
              lanel
                = t("layout.order.status")
                = f.select :status, options_for_select(option_for_status_order, @params_search[:status] ),
                    {include_blank: true}, class: "form-control", value: @params_search[:status]
              label
                  = f.text_field :name_or_address_or_email, value: @params_search[:name_or_address_or_email],
                      placeholder: t("layout.order.name_address_email"), class: "form-control"
              = f.submit t("layout.order.search") ,class: "btn btn-default"
      .row
        .col-sm-12
          table.table.table-striped.table-bordered.table-hover.dataTable.no-footer.dtr-inline aria-describedby="dataTables-example_info" role="grid" style=("width: 100%;") width="100%"
            thead
              tr role="row"
                th colspan="1" rowspan="1" = t("layout.order.email")
                th colspan="1" rowspan="1" = t("layout.order.name")
                th colspan="1" rowspan="1" = t("layout.order.address")
                th colspan="1" rowspan="1" = t("layout.order.phone_number")
                th colspan="1" rowspan="1" = t("layout.order.date")
                th colspan="1" rowspan="1" = t("layout.order.status")
                th colspan="1" rowspan="1"
            tbody
              - @orders.each do |order|
                tr role="row"
                  td = order.user.email
                  td = order.name
                  td = order.address
                  td = order.phone_number
                  td = order.created_format
                  td = t("model.order.status.#{order.status}")
                  td = link_to "#{t("layout.order.details")}", admin_order_path(order)
      .row.list-group
        .pull-right
          = paginate @orders, theme: "twitter-bootstrap-3"
      .row
        .col-sm-6
          #dataTables-example_paginate.dataTables_paginate.paging_simple_numbers
            ul.pagination

app/views/admin/orders/show.html.slim
.panel.panel-default
  .panel-heading
    = t("layout.order.order_infor")
  .panel-body
    #dataTables-example_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer
      .row
        table.table.no-footer.dtr-inline role="grid" style=("width: 100%;") width="100%"
          thead
            tr role="row"
              th colspan="1" rowspan="1" = t("layout.order.email")
              th colspan="1" rowspan="1" = t("layout.order.name")
              th colspan="1" rowspan="1" = t("layout.order.address")
              th colspan="1" rowspan="1" = t("layout.order.phone_number")
              th colspan="1" rowspan="1" = t("layout.order.date")
              th colspan="1" rowspan="1" = t("layout.order.status")
              tr role="row"
                td = @order.user.email
                td = @order.name
                td = @order.address
                td = @order.phone_number
                td = @order.created_format
                td = t("model.order.status.#{@order.status}")
.panel.panel-default
  .panel-heading
    = t("layout.order.order_details")
  .panel-body
    #dataTables-example_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer
      .row
        .col-sm-12
          table.table.table-hover.table-bordered
            thead
              tr
                th = t("layout.order.product")
                th = t("layout.order.quantity")
                th.text-center = t("layout.order.price")
                th.text-center = t("layout.order.total")
            tbody
              -@details.each do |detail|
                tr
                  td.col-sm-8.col-md-6
                    .media
                      a.thumbnail.pull-left href="#"
                        = image_tag detail.product.image.url(:thumb), class: "media-object"
                      .media-body
                        h4.media-heading = detail.product.name
                  td.col-sm-1.col-md-1 style=("text-align: center")
                    strong = detail.quantity
                  td.col-sm-1.col-md-1.text-center
                    strong = detail.price
                  td.col-sm-1.col-md-1.text-center.total_in_row
                    strong = detail.total
              tr
                td colspan="2"
                td
                  h3 = t("layout.order.total")
                td.text-right
                  h3
                    strong.total
          .pull-right
            - if @order.pending?
              = link_to reject_admin_order_path(@order), class: "btn btn-danger", method: :patch
                = t("layout.order.reject")
              = link_to approve_admin_order_path(@order), class: "btn btn-success", method: :patch
                = t("layout.order.approve")