config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: "home#index"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create"
  delete :logout, to: "sessions#destroy"
  get :cart, to: "cart#index"
  post "products/:product_id/rating", to: "rates#rating", as: :product_rating
  get "add_cart/:id_product", to: "sessions#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "sessions#remove_cart", as: :remove_cart
  put "update_cart", to: "sessions#update_cart", as: :update_cart
  put "update_hard_cart", to: "sessions#update_hard_cart", as: :update_hard_cart

  resources :orders, only: %i(index create)
  resources :history, only: :index
  resources :products, only: %i(index show)
  resources :categories, only: :show
  namespace :admin do
    resources :orders, only: %i(index show) do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :categories, except: %i(new create) do
      member do
        get "new", to: "categories#new", as: :new
        post "new", to: "categories#create", as: :create
      end
      resources :products
    end

    get :import_product, to: "products#import", as: :product_import
    post :import_product, to: "products#import_process", as: :product_import_process

    resources :charts, only: :index
  end
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  has_many :products, dependent: :destroy
  belongs_to :parent, class_name: Category.name, optional: true
  has_many :children, class_name: Category.name, foreign_key: :parent_id, dependent: :destroy

  validates :name, presence: true,
    length: {maximum: Settings.category.name_max_length}

  scope :list_parents, ->{where parent_id: nil}
  scope :ordered_by_name, ->{order name: :asc}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  include ApplicationHelper

  load_and_authorize_resource

  def index; end

  def new
    check_root_category
    @category_new = Category.new
  end

  def create
    if params[:id] == "0"
      @category_new = Category.new category_params
    else
      find_category
      @category_new = Category.new category_params.merge(parent_id: params[:id])
    end
    if @category_new.save
      flash[:success] = t("controller.category.create_success")
      category_redirect @category_new
    else
      check_root_category
      flash[:danger] = t("controller.category.create_fail")
      render :new
    end
  end

  def show
    @category_child = @category.children
  end

  def edit; end

  def update
    if @category.update category_params
      flash[:success] = t("controller.category.update_success")
      category_redirect @category
    else
      flash[:danger] = t("controller.category.update_fail")
      render :edit
    end
  end

  def destroy
    if category_has_no_product_are_being_ordered @category
      if @category.destroy
        flash[:success] = t("controller.category.delete_success")
      else
        flash[:danger] = t("controller.category.delete_error")
      end
    else
      flash[:notice] = t("controller.category.delete_fail")
    end
    category_redirect @category
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def category_redirect category
    if category.parent
      redirect_to admin_category_path category.parent
    else
      redirect_to admin_categories_path
    end
  end

  def check_root_category
    params[:id] == "0" ? @category = 0 : ""
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper

  layout "home"

  def show
    @category = Category.find_by id: params[:id]
    redirect_to root_path, notice: t("controller.category.not_found") unless @category
    list_id_product = get_all_product_by_category(@category, [])
    @products = Product.list_product(list_id_product).page(params[:page])
                       .per(Settings.product.per_page)
  end
end

app/views/admin/categories/edit.html.slim
.panel.panel-default
  .panel-heading = t("layout.category.edit_category")
  .panel-body
    .row
      .col-lg-12
        = form_for @category, url: admin_category_path, method: :patch do |f|
          .form-group
            label = t("layout.category.name")
            = f.text_field :name, class: "form-control"
          .form-group
            label = t("layout.category.description")
            = f.text_area :description, class: "form-control"
          button.btn.btn-default type="submit" = t("layout.category.save")

app/views/admin/categories/index.html.slim
.panel.panel-default
  .panel-heading
    = t("layout.category.header_index")
  .panel-body
    #dataTables-example_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer
      .row
        .col-sm-6
        .col-sm-6
          #dataTables-example_filter.dataTables_filter
      .row
        .col-sm-12
          = link_to new_admin_category_path(0), class: "btn btn-success"
            | New
          table.table.table-striped.table-bordered.table-hover.dataTable.no-footer.dtr-inline aria-describedby="dataTables-example_info" role="grid" style=("width: 100%;") width="100%"
            thead
              tr role="row"
                th colspan="1" rowspan="1" Name
                th colspan="1" rowspan="1" Description
                th colspan="1" rowspan="1" Details
                th colspan="1" rowspan="1" Action
            tbody
              - list_category.each do |category|
                tr role="row"
                  td = category.name
                  td = category.description
                  td
                    = link_to admin_category_path(category)
                      | #{t("layout.category.details")} (#{category.children.length})
                    = link_to admin_category_products_path(category)
                      | #{t("layout.category.products")} (#{category.products.length})
                  td
                    = link_to edit_admin_category_path(category)
                      span.btn.btn-info
                        i.fa.fa-edit
                    = link_to admin_category_path(category), method: :delete
                      span.btn.btn-danger
                        i.fa.fa-trash

app/views/admin/categories/new.html.slim
.panel.panel-default
  .panel-heading = t("layout.category.new_category")
  .panel-body
    .row
      .col-lg-12
        = form_for @category_new, url: create_admin_category_path(@category), method: :post do |f|
          .form-group
            label = t("layout.category.name")
            = f.text_field :name, class: "form-control"
          .form-group
            label = t("layout.category.description")
            = f.text_area :description, class: "form-control"
          button.btn.btn-default type="submit" = t("layout.category.save")

app/views/admin/categories/show.html.slim
.panel.panel-default
  .panel-heading
    = t("layout.order.header_index")
  .panel-body
    #dataTables-example_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer
      .row
        .col-sm-6
        .col-sm-6
          #dataTables-example_filter.dataTables_filter
      .row
        .col-sm-12
          = link_to new_admin_category_path(@category), class: "btn btn-success"
            = t("layout.category.new")
          table.table.table-striped.table-bordered.table-hover.dataTable.no-footer.dtr-inline aria-describedby="dataTables-example_info" role="grid" style=("width: 100%;") width="100%"
            thead
              tr role="row"
                th colspan="1" rowspan="1" = t("layout.category.name")
                th colspan="1" rowspan="1" = t("layout.category.description")
                th colspan="1" rowspan="1" = t("layout.category.details")
                th colspan="1" rowspan="1" = t("layout.category.actions")
            tbody
              - @category_child.each do |category|
                tr role="row"
                  td = category.name
                  td = category.description
                  td
                    = link_to admin_category_path(category)
                      | #{t("layout.category.details")} (#{category.children.length})
                    = link_to admin_category_products_path(category)
                      | #{t("layout.category.products")} (#{category.products.length})
                  td
                    = link_to edit_admin_category_path(category)
                      span.btn.btn-info
                        i.fa.fa-edit
                    = link_to admin_category_path(category), method: :delete
                      span.btn.btn-danger
                        i.fa.fa-trash