config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: "home#index"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create"
  delete :logout, to: "sessions#destroy"
  get :cart, to: "cart#index"
  post "products/:product_id/rating", to: "rates#rating", as: :product_rating
  get "add_cart/:id_product", to: "sessions#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "sessions#remove_cart", as: :remove_cart
  put "update_cart", to: "sessions#update_cart", as: :update_cart
  put "update_hard_cart", to: "sessions#update_hard_cart", as: :update_hard_cart

  resources :orders, only: %i(index create)
  resources :history, only: :index
  resources :products, only: %i(index show)
  resources :categories, only: :show
  namespace :admin do
    resources :orders, only: %i(index show) do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :categories, except: %i(new create) do
      member do
        get "new", to: "categories#new", as: :new
        post "new", to: "categories#create", as: :create
      end
      resources :products
    end

    get :import_product, to: "products#import", as: :product_import
    post :import_product, to: "products#import_process", as: :product_import_process

    resources :charts, only: :index
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :category
  has_many :comments
  has_many :reviews
  has_many :order_details

  attr_accessor :quantity_in_cart

  has_attached_file :image, default_url: Settings.product.default_image,
    styles: {medium: Settings.product.size_medium,
             thumb: Settings.product.size_thumb}

  validates_attachment :image,
    content_type: {content_type: Settings.product.image_accept}
  validates :name, presence: true,
    length: {maximum: Settings.product.name_max_length}
  validates :description, presence: true,
    length: {maximum: Settings.product.description_max_length}
  validates :price, presence: true
  validates :quantity, presence: true

  scope :ordered_by_name, ->{order name: :asc}
  scope :product_in_cart, ->(cart){where id: cart}
  scope :by_name, ->(query){where("name LIKE ?", "%#{query}%")}
  scope :by_name_or_desc, ->(query){where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")}
  scope :list_product, ->(query){where id: query}

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(Settings.product.number_header)
    (Settings.product.start_column..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = new
      product.attributes = row.to_hash.slice(*row.to_hash.keys)
      product.save
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise I18n.t("controller.product.unknown_file_type") + file.original_filename
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  include ApplicationHelper

  load_and_authorize_resource

  before_action :find_category, except: %i(import_process import)

  def index
    @params_search = params[:product] || {name_or_desc: ""}
    @products = @category.products.by_name_or_desc(@params_search[:name_or_desc])
                         .page(params[:page]).per(Settings.product.per_page)
  end

  def new
    @product = @category.products.new
  end

  def create
    @product = @category.products.new product_params
    if @product.save
      flash[:success] = t("controller.product.create_success")
      redirect_to admin_category_products_path @category
    else
      flash[:error] = t("controller.product.create_fail")
      render :new
    end
  end

  def edit; end

  def update
    if @product.update product_params
      flash[:success] = t("controller.product.update_success")
      redirect_to admin_category_products_path @category
    else
      flash[:error] = t("controller.product.update_fail")
      render :edit
    end
  end

  def show; end

  def destroy
    if product_are_not_being_ordered @product
      if @product.destroy
        flash[:success] = t("controller.product.delete_success")
      else
        flash[:danger] = t("controller.product.delete_error")
      end
    else
      flash[:notice] = t("controller.product.delete_fail")
    end
    redirect_to admin_category_products_path @category
  end

  def import_process
    unless params[:file]
      flash[:notice] = t("controller.product.file_not")
      redirect_to admin_product_import_path
      return
    end
    Product.import params[:file]
    flash[:success] = t("controller.product.import_success")
    redirect_to admin_categories_path
  end

  private

  def product_params
    params.require(:product).permit :name, :description, :price, :quantity,
      :image
  end

  def find_category
    @category = Category.find_by id: params[:category_id]
    return if @category
    flash[:notice] = t("controller.category.not_found")
    redirect_to admin_categories_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ApplicationHelper

  layout "home"

  def index
    @products = @q.result(distinct: true).page(params[:page])
                       .per(Settings.order.per_page)
  end

  def show
    @product = Product.find_by id: params[:id]
    redirect_to root_path, notice: t("controller.product.not_found") unless @product
    flash[:notice] = t("controller.product.recently_fail") unless add_recently_product @product
  end
end

app/views/admin/products/_form.html.slim
= form_for [:admin, @category, @product] do |f|
  .form-group
    label = t("layout.product.name")
    = f.text_field :name, class: "form-control"
  .form-group
    label = t("layout.product.description")
    = f.text_area :description, class: "form-control"
  .form-group
    label = t("layout.product.quantity")
    = f.number_field :quantity, class: "form-control"
  .form-group
    label = t("layout.product.price")
    = f.number_field :price, class: "form-control"
  .form-group
    label = t("layout.product.image")
    .row.current_image
      = image_tag @product.image.url(:medium)
    = f.file_field :image
  button.btn.btn-default type="submit" = t("layout.product.save")

app/views/admin/products/_product.html.slim
tr role="row"
  td = product.name
  td = image_tag product.image.url(:medium)
  td = product.description
  td = product.price
  td = product.quantity
  td
    = link_to edit_admin_category_product_path(@category, product)
      span.btn.btn-info
        i.fa.fa-edit
    = link_to admin_category_product_path(@category, product), method: :delete
      span.btn.btn-danger
        i.fa.fa-trash

app/views/admin/products/edit.html.slim
.panel.panel-default
  .panel-heading = t("layout.product.edit_product")
  .panel-body
    .row
      .col-lg-12
        =render "form"

app/views/admin/products/import.html.slim
.panel.panel-default
  .panel-body
    .row
      .col-lg-12
        h4 = t("layout.product.import_header")
        = form_tag admin_product_import_process_path, multipart: true, id: "form_import" do
          .form-group
            = file_field_tag :file
          .form-group
            = submit_tag t("layout.product.import"), class: "btn btn-success"

app/views/admin/products/index.html.slim
.panel.panel-default
  .panel-heading
    | #{t("layout.product.product_of")} #{@category.name}
  .panel-body
    #dataTables-example_wrapper.dataTables_wrapper.form-inline.dt-bootstrap.no-footer
      .row
        .col-sm-6
        .col-sm-6
          #dataTables-example_filter.dataTables_filter
      .row
        .col-sm-6
          = link_to new_admin_category_product_path(@category), class: "btn btn-success"
            | New
        .col-sm-6
          #dataTables-example_filter.dataTables_filter
            = form_for :product, method: :get do |f|
              = f.text_field :name_or_desc, value: @params_search[:name_or_address_or_email],
                placeholder: t("layout.product.name_or_desc"), class: "form-control"
              = f.submit t("layout.product.search") ,class: "btn btn-default"
        table.table.table-striped.table-bordered.table-hover.dataTable.no-footer.dtr-inline aria-describedby="dataTables-example_info" role="grid" style=("width: 100%;") width="100%"
          thead
            tr role="row"
              th colspan="1" rowspan="1" = t("layout.product.name")
              th colspan="1" rowspan="1" = t("layout.product.image")
              th colspan="1" rowspan="1" = t("layout.product.description")
              th colspan="1" rowspan="1" = t("layout.product.price")
              th colspan="1" rowspan="1" = t("layout.product.quantity")
              th colspan="1" rowspan="1" = t("layout.product.action")
          tbody
            = render partial: "product", collection: @products, as: :product
        .row
          .col-md-12
            .pull-right
              = paginate @products, theme: "twitter-bootstrap-3"

app/views/admin/products/new.html.slim
.panel.panel-default
  .panel-heading = t("layout.product.new_product.product_of")
  .panel-body
    .row
      .col-lg-12
        =render "form"