config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: "home#index"

  get :login, to: "sessions#new"
  post :login, to: "sessions#create"
  delete :logout, to: "sessions#destroy"
  get :cart, to: "cart#index"
  post "products/:product_id/rating", to: "rates#rating", as: :product_rating
  get "add_cart/:id_product", to: "sessions#add_cart", as: :add_cart
  get "remove_cart/:id_product", to: "sessions#remove_cart", as: :remove_cart
  put "update_cart", to: "sessions#update_cart", as: :update_cart
  put "update_hard_cart", to: "sessions#update_hard_cart", as: :update_hard_cart

  resources :orders, only: %i(index create)
  resources :history, only: :index
  resources :products, only: %i(index show)
  resources :categories, only: :show
  namespace :admin do
    resources :orders, only: %i(index show) do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :categories, except: %i(new create) do
      member do
        get "new", to: "categories#new", as: :new
        post "new", to: "categories#create", as: :create
      end
      resources :products
    end

    get :import_product, to: "products#import", as: :product_import
    post :import_product, to: "products#import_process", as: :product_import_process

    resources :charts, only: :index
  end
end

app/views/layouts/_categories_list.html.slim
li.collapsed.active
  a.category-link href="#{category_path(category)}"
    = category.name
  a.pull-right.drop-down data-toggle="collapse" data-target="#cat#{category.id}"
    - if category.children.any?
      span.pull-right.fa.fa-angle-down.fa-lg
      ul.nav.nav-list.nav-category.collapse.sub-menu id="cat#{category.id}"
        = render partial: "layouts/categories_list", collection: category.children, as: :category

app/views/layouts/_home_header.html.slim
  #gototop
  header#header
    .row
      .col-md-4
        h1
          = link_to root_path, class: "logo"
            = image_tag "logo-bootstrap-shoping-cart"
      .col-md-4
      .col-md-4.alignR
        p
          br/
          strong = t("layout.home.support")
  nav.navbar.navbar-inverse role="navigation"
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only
          span.icon-bar
          span.icon-bar
          span.icon-bar
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        = search_form_for @q, url: products_path, html: {class: "navbar-form navbar-left", method: :get} do |f|
          .input-group
            =f.search_field :name_cont, class: "form-control", placeholder: t("layout.home.search")
            #clone
            .input-group-btn
              button.btn.btn-default.btn-search type="submit"
                i.fa.fa-search-plus.fa-lg
        ul.nav.navbar-nav.navbar-right
          li
            p.navbar-text = t("layout.home.already_account")
          -if current_user
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#"
                b = current_user.name
                span.caret
              ul.dropdown-menu#logout-dp
                li
                  .row
                    .pull-right
                      =link_to "#{t('layout.session.logout')}", destroy_user_session_path, method: :delete, class: "btn btn-default"
          -else
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#"
                b = t("layout.session.login")
                span.caret
              ul#login-dp.dropdown-menu
                li
                  .row
                    .col-md-12
                      = form_for :user, url: session_path(:user), method: :post, html: {id: "login", class: "form"} do |f|
                        .form-group
                          label.sr-only = t("layout.session.email")
                          = f.email_field :email, class: "form-control", place_holder: t("layout.session.email")
                        .form-group
                          label.sr-only = t("layout.session.password")
                          = f.password_field :password, class: "form-control", place_holder: t("layout.session.password")
                          .help-block.text-right
                            = link_to t("layout.session.forget_password"), new_user_password_path
                        .form-group
                          = f.submit "#{t('layout.session.sign_in')}", class: "btn btn-primary btn-block"
                        .checkbox
                          label
                            = f.check_box :remember_me
                            = t("layout.session.keep_login")
                        = link_to t("layout.devise.sign_in_w_fb"), user_facebook_omniauth_authorize_path
                        br
                        = link_to t("layout.devise.sign_in_w_gg"), user_google_oauth2_omniauth_authorize_path

app/views/layouts/_section.html.slim
section.our_client
  hr.soften/
  h4.title.cntr
    span.text = t("layout.home.manufactures")
  hr.soften/
  .row
    .col-md-2
      a href="#"
        = image_tag "1"
    .col-md-2
      a href="#"
        = image_tag "2"
    .col-md-2
      a href="#"
        = image_tag "3"
    .col-md-2
      a href="#"
        = image_tag "4"
    .col-md-2
      a href="#"
        = image_tag "5"
    .col-md-2
      a href="#"
        = image_tag "6"
footer.footer
  .row
     .col-md-6.col-md-offset-6
      h5 = t("layout.home.history_title")
      = t("layout.home.history")

app/views/layouts/_sidebar.html.slim
#sidebar.col-md-3
  .well.well-small
    ul.nav.nav-list.nav-category
      = render partial: "layouts/categories_list", collection: list_category, as: :category
  br
  .well-small.well
    h4.text-center = t("layout.home.price_range")
    = search_form_for @q, url: products_path, html: {id: "product", method: :get} do |f|
      .form-group.row
        .col-md-6
          =f.search_field :price_gteq, type: "number", class: "form-control clone-item", placeholder: t("layout.home.from")
        .col-md-6
          =f.search_field :price_lteq, type: "number", class: "form-control clone-item", placeholder: t("layout.home.to")
      .form-group.row
        .col-md-12
          =f.button id: "search_button", type: "button", class: "btn btn-default"
            = t("layout.home.search")
  ul.nav.nav-list.promowrapper
    -if recently_product
      -recently_product.each do |product|
        li
          .thumbnail
            = link_to product_path(product), class: "zoomTool", title: t("layout.home.add_to_cart")
              span.fa.fa-search-plus
              = t("layout.home.quick_view")
            = image_tag product.image.url(:medium)
            .caption
              h4
                = product.name
                span.pull-right = product.price
        li style="border:0"   

app/views/layouts/_slide.html.slim
.well.np
  #myCarousel.carousel.slide.homCar
    .carousel-inner
      .item
        = image_tag "bootstrap_free-ecommerce"
      .item
        = image_tag "carousel1"
      .item.active
        = image_tag "carousel3"
      .item
        = image_tag "bootstrap-templates"
    a.left.carousel-control data-slide="prev" href="#myCarousel" ‹
    a.right.carousel-control data-slide="next" href="#myCarousel" ›

app/views/layouts/_trend.html.slim
        h3 = t("layout.home.trend_product")
        hr.soften/
        .row.list-group
          #newProductCar.carousel.slide
            .carousel-inner
              .item.active
                .row
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a.tag href="#"
                      a href="#"
                        = image_tag "bootstrap-ring"
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a.tag href="#"
                      a href="#"
                        = image_tag "i"
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a.tag href="#"
                      a href="#"
                        = image_tag "g"
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a href="#"
                        = image_tag "s"
              .item
                .thumbnails
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a href="#"
                        = image_tag "i"
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a href="#"
                        = image_tag "f"
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a href="#"
                        = image_tag "j"
                  .col-md-3
                    .thumbnail
                      a.zoomTool href="#" title=("#{t("layout.home.add_to_cart")}")
                        span.fa.fa-search-plus
                        = t("layout.home.quick_view")
                      a href="#"
                        = image_tag "j"
            a.left.carousel-control data-slide="prev" href="#newProductCar"  ‹
            a.right.carousel-control data-slide="next" href="#newProductCar"  ›

app/views/layouts/admin.html.slim
head
  title = t("layout.home.title")
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
  = javascript_include_tag "application", "data-turbolinks-track": "reload"
body
  .notifications.top-right
  #wrapper
    nav.navbar.navbar-default.navbar-static-top role="navigation" style=("margin-bottom: 0")
      .navbar-header
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to admin_orders_path, class: "navbar-brand"
          = t("layout.admin.title")
      ul.nav.navbar-top-links.navbar-right
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            -if current_user
              = current_user.name
            i.fa.fa-user.fa-fw
            i.fa.fa-caret-down
          ul.dropdown-menu.dropdown-user
            li
              a href="#"
                i.fa.fa-user.fa-fw
                | User Profile
            li
              =link_to destroy_user_session_path, method: :delete
                i.fa.fa-sign-out.fa-fw
                = t('layout.session.logout')
      .sidebar
        ul.nav.nav-list.nav-category
          li.collapsed.active
            = link_to admin_orders_path
               = t("layout.admin.orders")
          li.collapsed.active
            = link_to admin_categories_path
               = t("layout.admin.categories")
          li.collapsed.active
            = link_to admin_product_import_path
               = t("layout.admin.import_products")
          li.collapsed.active
            = link_to admin_charts_path
               = t("layout.admin.charts")
    #page-wrapper style=("min-height: 700px;")
      .container-fluid
        .row
          .col-lg-12
            = yield
- if flash
  -flash.each do |type, message|
    javascript:
      $('.top-right').notify({
        message: { text: "#{message}" }
      }).show();

app/views/layouts/application.html.slim
head
  title = t("layout.home.title")
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
  = javascript_include_tag "application", "data-turbolinks-track": "reload"
body
  = yield

app/views/layouts/devise.html.slim
head
  title = t("layout.home.title")
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
  = javascript_include_tag "application", "data-turbolinks-track": "reload"
body
  .container-home
    .notifications.top-right
    .main
      .col-md-offset-3.col-md-6
        = yield
    .copyright
      .container
        span
          = t("layout.home.copyright")
    a.gotop href="#"
      i.fa.fa-angle-double-up
- if flash
  -flash.each do |type, message|
    javascript:
      $('.top-right').notify({
        message: { text: "#{message}" }
      }).show();

app/views/layouts/home.html.slim
head
  title = t("layout.home.title")
  = csrf_meta_tags

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
  = javascript_include_tag "application", "data-turbolinks-track": "reload"
body
  #fb-root
  javascript:
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.0&appId=1911353699096147&autoLogAppEvents=1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  .container-home
    .notifications.top-right
    .navbar.navbar-fixed-top
      .topNav
        .container
          .alignR
            = link_to root_path, class: "active"
              span.fa.fa-home
              = t("layout.home.home")
            = link_to edit_user_registration_path
              span.fa.fa-user
              = t("layout.home.my_account")
            = link_to history_index_path
              span.fa.fa-history
              = t("layout.home.history")
            = link_to new_user_registration_path
              span.fa.fa-user-edit
              = t("layout.home.free_register")
            a href="contact.html"
              span.fa.fa-envelope
              = t("layout.home.contact_us")
            = link_to cart_path
              span.fa.fa-shopping-cart
              span.number-item
                -if current_cart
                  | #{total_cart } #{t("layout.home.item")}
    = yield
    .copyright
      .container
        span
          = t("layout.home.copyright")
    a.gotop href="#"
      i.fa.fa-angle-double-up
- if flash
  -flash.each do |type, message|
    javascript:
      $('.top-right').notify({
        message: { text: "#{message}" }
      }).show();